# Generated by Django 6.0.1 on 2026-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=12)),
                ('proyecto', models.TextField()),
                ('empresa', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Modificacion')),
            ],
        ),
    ]
