# Generated by Django 6.0.1 on 2026-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
