# Generated by Django 6.0.1 on 2026-03-19 05:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario Contacto', 'verbose_name_plural': 'Comentarios Contactos'},
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Folio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.blog', verbose_name='Blog')),
            ],
        ),
    ]
