# Generated by Django 6.0.1 on 2026-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_remove_cotizacion_fecha_blog_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-created'], 'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
