# Generated by Django 6.0.1 on 2026-04-01 21:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_alter_cotizacion_options_alter_cotizacion_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='blog',
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='mensaje',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificacion'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_servicio', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'DescripcionServicios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('mensaje', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('calificacion', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='resena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.resena'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
