# Generated by Django 6.0.1 on 2026-04-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_remove_respuesta_blog_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-created'], 'verbose_name': 'Resena', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
