# Generated by Django 6.0.1 on 2026-04-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_alter_resena_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion',
            name='nombre',
        ),
    ]
