# Generated by Django 6.0.1 on 2026-04-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_alter_cotizacion_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='resena',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.cotizacion'),
        ),
    ]
