# Generated by Django 6.0.1 on 2026-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_remove_respuesta_resena_respuesta_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('enviado', 'Enviado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('enviado', 'Enviado')], default='pendiente', max_length=10),
        ),
    ]
